version: '3'
services:

  fastapi:
    image: goplan/fastapi:python3.10
    build:
      context: ../../../fastapi
      dockerfile: Dockerfile
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    environment:
      PORT: ${FASTAPI_PORT}
    volumes:
      - ./fastapi/app:/app
    command: [ "/start-reload.sh" ]
    restart: unless-stopped