version: '3'
services:

  #  db:
  #    image: postgres:15
  #    restart: always
  #    environment:
  #      POSTGRES_USER: example
  #      POSTGRES_PASSWORD: example
  #      POSTGRES_DB: financialstatements

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27020:27017

  fastapi:
    image: goplan/fastapi:python3.10
    build:
      context: ../../../fastapi
      dockerfile: Dockerfile
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    environment:
      PORT: ${FASTAPI_PORT}
    volumes:
      - ./fastapi/app:/app
    command: [ "/start-reload.sh" ]
    restart: unless-stopped