version: '3'
services:

#  react:
#    image: goplan/react:dev
#    build:
#      context: react
#    expose:
#      - ${REACT_PORT}
#    ports:
#      - ${REACT_PORT}:${REACT_PORT}
#    environment:
#      PORT: ${REACT_PORT}
#      CI: true
#    volumes:
#      - ./react:/app
#    command: [ "npm", "start" ]
#    restart: unless-stopped

  fastapi:
    image: goplan/fastapi:python3.10
    build:
      context: ../../../fastapi
      dockerfile: Dockerfile
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    environment:
      PORT: ${FASTAPI_PORT}
    volumes:
      - ./fastapi/app:/app
    command: [ "/start-reload.sh" ]
    restart: unless-stopped